version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mudar-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: mudar_user
      POSTGRES_PASSWORD: mudar_password
      POSTGRES_DB: mudar_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
